--disable-search-engine-collection
--enable-gpu-rasterization
--enable-quic
--enable-zero-copy
--enable-smooth-scrolling
--force-dark-mode
--hide-crashed-bubble
--hide-fullscreen-exit-ui
--ignore-gpu-blocklist
--remove-tabsearch-button
--start-maximized
--enable-experimental-webassembly-features
--enable-experimental-web-platform-features
--enable-native-gpu-memory-buffers
--javascript-harmony
--no-default-browser-check
--no-first-run
--disable-gpu-driver-bug-workarounds
--new-canvas-2d-api
--process-per-site

--enable-wayland-ime
--wayland-text-input-version=3

--ozone-platform=wayland

--enable-features=UseOzonePlatform,WaylandWindowDecorations,AcceleratedVideoEncoder,VaapiVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxGL,CanvasOopRasterization,AcceleratedVideoDecodeLinuxZeroCopyGL,EnableLazyLoadImageForInvisiblePage,FluentOverlayScrollbar,FluentScrollbar,V8VmFuture
--disable-features=OverlayScrollbar,UseChromeOSDirectVideoDecoder

--max-connections-per-host=15
--extension-mime-request-handling=always-prompt-for-install
--show-avatar-button=never
