--enable-wayland-ime
--wayland-text-input-version=3

--ozone-platform=wayland

--enable-features=UseOzonePlatform,WaylandWindowDecorations
--disable-features=OverlayScrollbar,UseChromeOSDirectVideoDecoder